<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    {{-- Re-generated by Shubham Raj for SEO purposes start --}}
    {{-- Set the character encoding to UTF-8 for proper text display and support for various languages and scripts. --}}
    <meta charset="UTF-8" />
    {{-- Set the viewport meta tag to optimize the display and user experience on mobile devices.
        - 'width=device-width' ensures the content fits the device's screen width.
        - 'initial-scale=1' sets the initial zoom level to 100%, preventing unwanted zooming.
        - 'minimum-scale=1' prevents users from zooming out beyond the default scale.
        - 'maximum-scale=1' prevents users from zooming in beyond the default scale.
        - 'viewport-fit=cover' ensures content fits within the entire viewport, accommodating notches and rounded corners. --}}
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    {{-- Use the X-UA-Compatible meta tag to specify the desired rendering mode for Internet Explorer.
         Setting 'IE=edge' ensures the latest available rendering engine is used, enhancing compatibility. --}}
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    {{-- Control search engine behavior using the robots meta tag.
         - 'index' indicates the page should be indexed in search results.
         - 'follow' suggests that search engines should follow links on the page and crawl linked pages.
         - 'max-image-preview:large' instructs search engines to display large image previews.
         - 'max-snippet:-1' sets no maximum limit for text snippets in search results.
         - 'max-video-preview:-1' sets no maximum limit for video previews in search results. --}}
    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    {{-- Provide the Cross-Site Request Forgery (CSRF) token for security in dynamic web applications.
         This token helps protect against unauthorized actions that can be performed on behalf of the user. --}}
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    {{-- Website Info --}}
    <title>@yield ('title', config('app_settings.frontend.seo.page.home.title'))</title>
    <meta name="description"
        content="@yield ('description', config('app_settings.frontend.seo.page.home.description'))" />
    <meta name="keywords" content="@yield ('keywords', config('app_settings.frontend.seo.page.home.keywords'))" />
    <meta name="author" content="@yield ('author', config('app_settings.frontend.seo.page.home.author'))" />

    {{-- Open Graph Tags --}}
    <meta property="og:locale" content="@yield ('locale', config('app_settings.frontend.seo.page.home.locale'))" />
    <meta property="og:type" content="@yield ('type', config('app_settings.frontend.seo.page.home.type'))" />

    <meta property="og:title" content="@yield ('title', config('app_settings.frontend.seo.page.home.title'))" />
    <meta property="og:description"
        content="@yield ('description', config('app_settings.frontend.seo.page.home.description'))" />
    <meta property="og:url" content="{{ URL::current() }}" />
    <meta property="og:site_name" content="{{ config('app_settings.frontend.app.name') }}" />
    <meta property="article:modified_time"
        content="@yield ('modified_time', config('app_settings.frontend.seo.page.home.modified_time'))" />

    <meta property="og:image"
        content="@yield (asset('image'), asset(config('app_settings.frontend.seo.page.home.image')))" />
    <meta property="og:image:width" content="1024" />
    <meta property="og:image:height" content="512" />
    <meta property="og:image:type" content="image/png" />

    {{-- Twitter Card Tags --}}
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="@yield ('title', config('app_settings.frontend.seo.page.home.title'))" />
    <meta name="twitter:description"
        content="@yield ('description', config('app_settings.frontend.seo.page.home.description'))" />
    <meta name="twitter:image"
        content="@yield (asset('image'), asset(config('app_settings.frontend.seo.page.home.image')))" />
    <meta name="twitter:site" content="{{ '@' . config('app_settings.frontend.app.contact.username.twitter') }}" />
    <meta name="twitter:label1" content="Est. reading time" />
    <meta name="twitter:data1" content="10 minutes" />

    <!-- Web App Manifest and PWA Configuration -->
    {{-- Using the Web App Manifest and defining icons with dimensions in the manifest.json file is the recommended approach for modern websites when it comes to providing icons and other metadata for progressive web apps (PWAs). This method provides a more centralized and standardized way to manage icons and other PWA-related settings. --}}
    <!-- Web App Manifest for PWA -->
    <link rel="manifest" href="{{ route('manifest.json') }}">

    <!-- PWA Appearance and Behavior Settings -->
    <meta name="theme-color"
        content="@yield ('description', config('app_settings.frontend.app.manifest.theme_color'))" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-title" content="{{ config('app_settings.frontend.app.short_name') }}" />
    <meta name="application-name" content="{{ config('app_settings.frontend.app.short_name') }}" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />

    <!-- Favicon and Pinned Tab Icon Configuration -->
    <!-- Favicon for browsers -->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Apple touch icon for iOS devices -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('pwa/apple-touch-icon.png') }}">
    <!-- Favicon in PNG format for various sizes -->
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('pwa/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('pwa/favicon-16x16.png') }}">
    <!-- Use mask icon for Safari pinned tab -->
    <link rel="mask-icon" href="{{ asset('pwa/safari-pinned-tab.svg') }}" color="#c26f12">

    <!-- Common <link rel> tags for SEO -->
    <!-- Canonical Link Tag: Prevent duplicate content issues by specifying the preferred version of the page. -->
    <link rel="canonical" href="{{ URL::current() }}">


    <!-- Google Site Verification for ownership -->
    @foreach (config('app_settings.frontend.seo.website_ownership_verification_meta_code.google') as $userGmail => $metaTagCode)
        <meta name="google-site-verification" content="{{ $metaTagCode }}" />
    @endforeach

    <!-- Verify ownership with Microsoft's Bing Webmaster Tools -->
    @php $num = 0 @endphp {{-- For numbering like- msvalidate.01.02.03 --}}
    @foreach (config('app_settings.frontend.seo.website_ownership_verification_meta_code.bing') as $userGmail => $metaTagCode)
        @php $num++ @endphp
        <meta name="msvalidate.0{{ $num }}" content="{{ $metaTagCode }}" />
    @endforeach

    <!-- Verify ownership with Pinterest -->
    @foreach (config('app_settings.frontend.seo.website_ownership_verification_meta_code.pinterest') as $userGmail => $metaTagCode)
        <meta name="p:domain_verify" content="{{ $metaTagCode }}" />
    @endforeach

    {{-- <!-- Alternate Media Tags: Specify alternative media resources, such as feeds or print versions. -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="https://www.example.com/rss-feed.xml">
    <link rel="alternate" media="print" href="https://www.example.com/print-version">

    <!-- Alternate AMP (Accelerated Mobile Pages) Tag: Link to the AMP version of the page. -->
    <link rel="amphtml" href="https://www.example.com/amp-version"> --}}

    {{-- Re-generated by Shubham Raj for SEO purposes end --}}

    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/bootsnav.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/megamenu.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/responsive.css') }}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('assets/css/owl.carousel.css') }} ">
    <link rel="stylesheet" href="{{ asset('assets/css/owl.theme.default.css') }} ">

    <link href="{{ asset('assets/exzoom/jquery.exzoom.css') }}" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="{{ asset('assets/css/jquery-ui.css') }} ">
</head>

<body>

    @include('layouts.includes.users.header')
    @yield('content')
    @include('layouts.includes.users.footer')

    <a href="#" class="scrollup"><i class="fas fa-arrow-circle-up"></i></a>
    <script src="{{ asset('assets/js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ asset('assets/js/popper.min.js') }}"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/bootsnav.js') }}"></script>
    <script src="{{ asset('assets/js/megamenu.js') }}"></script>
    <script src="{{ asset('assets/js/owl.carousel.js') }}"></script>
    <script src="{{ asset('assets/exzoom/jquery.exzoom.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                dots: true,
                responsiveClass: true,
                thumbs: true,
                thumbsPrerendered: true,
                navText: ["<img src={{ asset('assets/images/arrow-left.png') }}>",
                    "<img src={{ asset('assets/images/arrow-right.png') }}>"
                ],
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 7
                    },
                    1000: {
                        items: 7
                    }
                }
            });

        });
    </script>

    <script>
        $("#accordion").on("hide.bs.collapse show.bs.collapse", e => {
            $(e.target)
                .prev()
                .find("i:last-child")
                .toggleClass("fa-minus fa-plus");
        });
    </script>


    <script src="{{ asset('assets/js/jquery-ui.js') }}"></script>

    <!-- ✅ load Slick ✅ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
        integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="{{ asset("assets/js/custom.js$vJs") }}"></script>

    <script>
        $(window).on('load', function() {

            var delayMs = 1000; // 150000 delay in milliseconds
            setTimeout(function() {
                const canShowInquiryModal = getCookie('showInquiryModal');

                // If cookie not set then show modal
                if (!canShowInquiryModal) {
                    $('#inqueryModal').modal('show');
                    setCookie('showInquiryModal', true, 60 * 30); // 30 min cookie
                }

            }, delayMs);
        });
    </script>

    <script>
        $(document).ready(function() {
            $("#dam_return a").click(function() {
                var value = $(this).html();
                var input = $('#dam');
                input.val(value);
            });
        });

        $('#myDIV').hide()
        jQuery('#dam').on('click', function() {
            jQuery('#myDIV').toggle();
        })
    </script>

    <script>
        function myFunction() {
            var x = document.getElementById("myDIV");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>

    @yield('scripts')
    @livewireScripts
</body>

</html>
